### PR TITLE
refactor: add function to display popUp

### PR DESCRIPTION
**Pull request by aleacevedo**
## Changelog

Implement function to displayPopUps

### Type of changes included:

- [ ] Components
- [ ] Business Logic
- [ ] Bug fixes
- [ ] Styling
- [x] Code Refactor

### CODE REVIEW

**Review by tomiir — COMMENTED** [review]
Do not merge. Need to test this

**Comment by riveign** [comment]
https://www.loom.com/share/31eeffdc9eba4397869382619340617f Found this bug after installing

**Comment by riveign** [comment]
Also the sonic swaps are not working in this version, this are the screenshots that appear in the consoles
Screen Shot 2022-04-14 at 10 51 34
Screen Shot 2022-04-14 at 10 51 19

**Review by tomiir — APPROVED** [review]
missing implementation on the controller modules themselves

**Pull request merged**
